version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      # solo exponer los puertos necesarios al exterior
      - 8222:8222

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src #Hot reload
    command: npm run start:dev
    environment:
      - PORT=3000
      - PRODUCTS_MICROSERVICE_HOST=localhost
      - PRODUCTS_MICROSERVICE_PORT=3001
      - ORDERS_MICROSERVICE_HOST=localhost
      - ORDERS_MICROSERVICE_PORT=3002
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223

  products-ms:
    build: ./products-ms
    ports:
      - 3001:3001
    volumes:
      - ./products-ms/src:/usr/src/app/src #Hot reload
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: ./orders-ms
    depends_on:
      - orders-db
    ports:
      - 3002:3002
    volumes:
      - ./orders-ms/src:/usr/src/app/src #Hot reload
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - DATABASE_URL=postgresql://myuser:mypassword@orders-db:5432/ordersdb?schema=public
      - PRODUCTS_MICROSERVICE_HOST=localhost
      - PRODUCTS_MICROSERVICE_PORT=3001

  orders-db:
    image: postgres:14.3
    container_name: orders_database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ordersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  payments-ms:
      build: ./payments-ms
      ports:
        - 3003:3003
      volumes:
        - ./payments-ms/src:/usr/src/app/src #Hot reload
      command: npm run start:dev
      environment:
        - PORT=${PAYMENTS_MS_PORT}
        - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
        - STRIPE_SECRET=${STRIPE_SECRET}
        - SECRET_ENDPOINT=${SECRET_ENDPOINT}
        - URL_SUCCESS=${URL_SUCCESS}
        - URL_CANCEL=${URL_CANCEL}
        # - PRODUCTS_MICROSERVICE_HOST=localhost
        # - PRODUCTS_MICROSERVICE_PORT=3001

  mongo:
    image: mongo:latest
    container_name: auth_database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db

  auth-ms:
    build: ./auth-ms
    ports:
      - 3004:3004
    volumes:
      - ./auth-ms/src:/usr/src/app/src #Hot reload
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - MONGO_URL=${MONGO_URL}
      - SECRET_TOKEN=${SECRET_TOKEN}

volumes:
  pgdata:
